# Generated by Django 3.2.12 on 2022-03-29 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FomoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
