# Generated by Django 4.0.2 on 2022-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FomoApp', '0002_auto_20220329_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadlinestable',
            name='deadlineid',
            field=models.AutoField(db_column='deadlineID', primary_key=True, serialize=False),
        ),
    ]
