# Generated by Django 4.0.2 on 2022-03-30 16:16

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('FomoApp', '0004_delete_attendancetable_alter_deadlinestable_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_days',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), blank=True, max_length=77, null=True, size=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='available_hours',
            field=django_mysql.models.ListCharField(models.CharField(max_length=6), blank=True, max_length=49, null=True, size=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='break_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ics_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_session',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
