# Generated by Django 4.0.2 on 2022-03-30 19:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('FomoApp', '0005_delete_attendancetable_alter_profile_available_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_hours',
            field=django_mysql.models.ListCharField(models.CharField(max_length=6), blank=True, max_length=98, null=True, size=14),
        ),
    ]
