# Generated by Django 4.0.2 on 2022-03-31 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FomoApp', '0008_delete_attendancetable_alter_eventstable_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventstable',
            old_name='userid',
            new_name='username',
        ),
    ]
