# Generated by Django 4.0.2 on 2022-03-31 20:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('FomoApp', '0009_delete_attendancetable_and_more'),
    ]

    operations = [
        
    ]
